Imports Microsoft.VisualBasic
Imports Telerik.Web.UI
Imports System.Reflection
Imports System.Data.SqlClient
Imports System.Data.SqlTypes
Imports System.Net.Mail
Imports System.Data



Public Class WebAppPageBO
    Inherits System.Web.UI.Page

    Protected Sub Page_Load(sender As Object, e As System.EventArgs) Handles Me.Load
        If Not (IsPostBack) Then
            If Utility.VerInt32(RetUserInfo("ID")) = 0 Then
                Response.Redirect("/adminlogin.aspx")
            End If
        End If
    End Sub

    Public Sub ExportGrid(ByVal FileName As String, ByVal RadGrid1 As RadGrid, Optional ByVal ShowAllColumnsWithValue As Boolean = True)
        RadGrid1.ExportSettings.FileName = FileName
        RadGrid1.ExportSettings.IgnorePaging = True
        RadGrid1.ExportSettings.OpenInNewWindow = True
        RadGrid1.ExportSettings.ExportOnlyData = True

        RadGrid1.MasterTableView.AllowFilteringByColumn = False
        RadGrid1.MasterTableView.AllowSorting = False
        RadGrid1.MasterTableView.CommandItemDisplay = GridCommandItemDisplay.None

        For Each C As GridColumn In RadGrid1.Columns
            If C.UniqueName.ToLower.ToString() = "duplicate" Or
               C.UniqueName.ToLower.ToString() = "delete" Or
               C.UniqueName.ToLower.ToString() = "edit" Then
                C.Display = False
            Else
                If ShowAllColumnsWithValue Then C.Display = True
            End If

        Next
        For Each C As GridColumn In RadGrid1.MasterTableView.AutoGeneratedColumns
            If C.UniqueName.ToLower.ToString() = "duplicate" Or
                C.UniqueName.ToLower.ToString() = "delete" Or
                C.UniqueName.ToLower.ToString() = "edit" Then
                C.Display = False
            Else
                If ShowAllColumnsWithValue Then C.Display = True
            End If
        Next
        For Each C As GridColumn In RadGrid1.MasterTableView.RenderColumns
            If C.UniqueName.ToLower.ToString() = "duplicate" Or
               C.UniqueName.ToLower.ToString() = "delete" Or
               C.UniqueName.ToLower.ToString() = "edit" Then
                C.Display = False
            Else
                If ShowAllColumnsWithValue Then C.Display = True
            End If
        Next
        RadGrid1.Rebind()
        RadGrid1.ExportSettings.Excel.Format = GridExcelExportFormat.ExcelML
        RadGrid1.ExportSettings.Excel.FileExtension = "xls"
        RadGrid1.MasterTableView.ExportToExcel()
        'RadGrid1.MasterTableView.ExportToCSV()
    End Sub

    Public Sub ClearGridConfiguration(ByVal PageName As String, ByVal UserId As Integer, ByVal GridName As String, ByVal RadGrid1 As RadGrid, Optional ByVal ResetColumns As Boolean = True)

        ExecuteSQL("Delete from User_Grid_Configurations where ID_user=" & UserId & " and page_name='" & PageName.Replace("/", "_") & "' and grid_name='" & GridName & "'")
        If ResetColumns Then ShowAllColumns(RadGrid1)
    End Sub


    Public Sub SaveGrid(ByVal PageName As String, ByVal UserId As Integer, ByVal GridName As String, ByVal RadGrid1 As RadGrid)

        ClearGridConfiguration(PageName, UserId, GridName, RadGrid1, False)

        For Each C As GridColumn In RadGrid1.Columns
            ExecuteSQL("insert into User_Grid_Configurations (ID_user,page_name,grid_name,column_name,display) values " &
                       "(" & UserId & ",'" & PageName.Replace("/", "_") & "','" & GridName & "','" & C.UniqueName & "'," & IIf(C.Display = True, 1, 0) & ")")
        Next
        For Each C As GridColumn In RadGrid1.MasterTableView.AutoGeneratedColumns
            ExecuteSQL("insert into User_Grid_Configurations (ID_user,page_name,grid_name,column_name,display) values " &
                       "(" & UserId & ",'" & PageName.Replace("/", "_") & "','" & GridName & "','" & C.UniqueName & "'," & IIf(C.Display = True, 1, 0) & ")")
        Next
    End Sub

    Private Sub ShowAllColumns(ByVal RadGrid1 As RadGrid)
        For Each C As GridColumn In RadGrid1.Columns
            C.Display = True
        Next

        For Each C As GridColumn In RadGrid1.MasterTableView.AutoGeneratedColumns
            C.Display = True
        Next
    End Sub


    Public Sub LoadGrid(ByVal PageName As String, ByVal UserId As Integer, ByVal GridName As String, ByVal RadGrid1 As RadGrid)

        Dim blnFind As Boolean
        Dim dt As New DataTable
        Dim oCon As SqlConnection = GetConn()
        dt = GetDt("Select * from User_Grid_Configurations where ID_user=" & UserId & " and page_name='" & PageName.Replace("/", "_") & "' and grid_name='" & GridName & "'", oCon)
        'For Each C As GridColumn In RadGrid1.Columns
        '    C.CurrentFilterFunction = GridKnownFunction.Contains
        '    C.AutoPostBackOnFilter = True
        'Next
        'For Each C As GridColumn In RadGrid1.MasterTableView.AutoGeneratedColumns
        '    C.CurrentFilterFunction = GridKnownFunction.Contains
        '    C.AutoPostBackOnFilter = True
        'Next
        'scorro il datatable
        For Each Orow As DataRow In dt.Rows
            blnFind = False
            For Each C As GridColumn In RadGrid1.Columns

                If Orow("column_name").ToString.ToUpper() = C.UniqueName.ToUpper Then
                    C.Display = Orow("display")
                    blnFind = True
                End If
            Next
            If Not (blnFind) Then
                For Each C As GridColumn In RadGrid1.MasterTableView.AutoGeneratedColumns
                    If Orow("column_name").ToString.ToUpper() = C.UniqueName.ToUpper Then
                        C.Display = Orow("display")
                        blnFind = True
                    End If
                Next
            End If
        Next
        'RadGrid1.MasterTableView.PagerStyle.Mode = Telerik.Web.UI.GridPagerMode.NextPrevAndNumeric
        RadGrid1.MasterTableView.PagerStyle.Position = Telerik.Web.UI.GridPagerPosition.TopAndBottom
        RadGrid1.MasterTableView.ItemStyle.Wrap = False
        'RadGrid1.MasterTableView.CommandItemSettings.ShowAddNewRecordButton = False 
        'RadGrid1.MasterTableView.CommandItemSettings.ShowExportToCsvButton = True
        'RadGrid1.MasterTableView.CommandItemSettings.ShowExportToExcelButton = True
        'RadGrid1.MasterTableView.CommandItemSettings.ShowExportToPdfButton = True
        'RadGrid1.MasterTableView.CommandItemSettings.ShowExportToWordButton = True
        'RadGrid1.MasterTableView.CommandItemDisplay = GridCommandItemDisplay.TopAndBottom
        RadGrid1.MasterTableView.ShowGroupFooter = True
        RadGrid1.MasterTableView.EnableHeaderContextFilterMenu = True
        RadGrid1.ShowGroupPanel = True
        RadGrid1.ShowStatusBar = True
        'RadGrid1.ExportSettings.ExportOnlyData = True
        'RadGrid1.ExportSettings.OpenInNewWindow = True
        'RadGrid1.ExportSettings.IgnorePaging = True
        'RadGrid1.ExportSettings.HideStructureColumns = True
        'RadGrid1.GridLines = GridLines.Both
        'RadGrid1.Rebind()
        oCon.Close()
        oCon.Dispose()
    End Sub
End Class
