/* tslint:disable */
/* eslint-disable */
/**
 * BotDashboard API
 * API per la gestione del Bot Dashboard con telemetria, comandi e statistiche real-time
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BotSessionEventRequest } from '../models';
// @ts-ignore
import type { BotSessionEventResponse } from '../models';
// @ts-ignore
import type { PcStart } from '../models';
// @ts-ignore
import type { ProblemDetails } from '../models';
/**
 * BotSessionApi - axios parameter creator
 */
export const BotSessionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get active bot sessions.
         * @param {string} [computer] Optional computer name filter
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBotSessionActiveGet: async (computer?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/BotSession/active`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (computer !== undefined) {
                localVarQueryParameter['computer'] = computer;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Mark inactive sessions as stopped (background job endpoint).
         * @param {number} [inactivityMinutes] Minutes of inactivity before marking as stopped
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBotSessionCleanupInactivePost: async (inactivityMinutes?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/BotSession/cleanup-inactive`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (inactivityMinutes !== undefined) {
                localVarQueryParameter['inactivityMinutes'] = inactivityMinutes;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Event Types:  - START: Bot session started (creates PC_Start record)  - STOP: Bot session ended (updates PC_Start, creates Stats and Stats_Margine)  - HEARTBEAT: Periodic update (updates session data, creates Stats_Margine snapshot)    Example START request:  ```json  {    \"eventType\": \"START\",    \"computer\": \"BOT-PC-01\",    \"userId\": 1,    \"botVersion\": \"2.5.3\",    \"balance\": 1000.00,    \"reason\": \"Manual\"  }  ```    Example STOP request:  ```json  {    \"eventType\": \"STOP\",    \"computer\": \"BOT-PC-01\",    \"userId\": 1,    \"balance\": 1250.00,    \"margine\": 250.00,    \"reason\": \"Target reached\",    \"totalHands\": 150,    \"totalWins\": 75,    \"totalLosses\": 70,    \"totalTies\": 5,    \"maxProfit\": 280.00,    \"maxDrawdown\": -50.00  }  ```
         * @summary Process a bot session event (START, STOP, HEARTBEAT).
         * @param {BotSessionEventRequest} [botSessionEventRequest] Session event data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBotSessionEventPost: async (botSessionEventRequest?: BotSessionEventRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/BotSession/event`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(botSessionEventRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Quick ping to verify the service is running.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBotSessionPingGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/BotSession/ping`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BotSessionApi - functional programming interface
 */
export const BotSessionApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BotSessionApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get active bot sessions.
         * @param {string} [computer] Optional computer name filter
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBotSessionActiveGet(computer?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PcStart>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiBotSessionActiveGet(computer, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BotSessionApi.apiBotSessionActiveGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Mark inactive sessions as stopped (background job endpoint).
         * @param {number} [inactivityMinutes] Minutes of inactivity before marking as stopped
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBotSessionCleanupInactivePost(inactivityMinutes?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiBotSessionCleanupInactivePost(inactivityMinutes, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BotSessionApi.apiBotSessionCleanupInactivePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Event Types:  - START: Bot session started (creates PC_Start record)  - STOP: Bot session ended (updates PC_Start, creates Stats and Stats_Margine)  - HEARTBEAT: Periodic update (updates session data, creates Stats_Margine snapshot)    Example START request:  ```json  {    \"eventType\": \"START\",    \"computer\": \"BOT-PC-01\",    \"userId\": 1,    \"botVersion\": \"2.5.3\",    \"balance\": 1000.00,    \"reason\": \"Manual\"  }  ```    Example STOP request:  ```json  {    \"eventType\": \"STOP\",    \"computer\": \"BOT-PC-01\",    \"userId\": 1,    \"balance\": 1250.00,    \"margine\": 250.00,    \"reason\": \"Target reached\",    \"totalHands\": 150,    \"totalWins\": 75,    \"totalLosses\": 70,    \"totalTies\": 5,    \"maxProfit\": 280.00,    \"maxDrawdown\": -50.00  }  ```
         * @summary Process a bot session event (START, STOP, HEARTBEAT).
         * @param {BotSessionEventRequest} [botSessionEventRequest] Session event data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBotSessionEventPost(botSessionEventRequest?: BotSessionEventRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BotSessionEventResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiBotSessionEventPost(botSessionEventRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BotSessionApi.apiBotSessionEventPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Quick ping to verify the service is running.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBotSessionPingGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiBotSessionPingGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BotSessionApi.apiBotSessionPingGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BotSessionApi - factory interface
 */
export const BotSessionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BotSessionApiFp(configuration)
    return {
        /**
         * 
         * @summary Get active bot sessions.
         * @param {string} [computer] Optional computer name filter
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBotSessionActiveGet(computer?: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<PcStart>> {
            return localVarFp.apiBotSessionActiveGet(computer, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Mark inactive sessions as stopped (background job endpoint).
         * @param {number} [inactivityMinutes] Minutes of inactivity before marking as stopped
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBotSessionCleanupInactivePost(inactivityMinutes?: number, options?: RawAxiosRequestConfig): AxiosPromise<any> {
            return localVarFp.apiBotSessionCleanupInactivePost(inactivityMinutes, options).then((request) => request(axios, basePath));
        },
        /**
         * Event Types:  - START: Bot session started (creates PC_Start record)  - STOP: Bot session ended (updates PC_Start, creates Stats and Stats_Margine)  - HEARTBEAT: Periodic update (updates session data, creates Stats_Margine snapshot)    Example START request:  ```json  {    \"eventType\": \"START\",    \"computer\": \"BOT-PC-01\",    \"userId\": 1,    \"botVersion\": \"2.5.3\",    \"balance\": 1000.00,    \"reason\": \"Manual\"  }  ```    Example STOP request:  ```json  {    \"eventType\": \"STOP\",    \"computer\": \"BOT-PC-01\",    \"userId\": 1,    \"balance\": 1250.00,    \"margine\": 250.00,    \"reason\": \"Target reached\",    \"totalHands\": 150,    \"totalWins\": 75,    \"totalLosses\": 70,    \"totalTies\": 5,    \"maxProfit\": 280.00,    \"maxDrawdown\": -50.00  }  ```
         * @summary Process a bot session event (START, STOP, HEARTBEAT).
         * @param {BotSessionEventRequest} [botSessionEventRequest] Session event data
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBotSessionEventPost(botSessionEventRequest?: BotSessionEventRequest, options?: RawAxiosRequestConfig): AxiosPromise<BotSessionEventResponse> {
            return localVarFp.apiBotSessionEventPost(botSessionEventRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Quick ping to verify the service is running.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBotSessionPingGet(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiBotSessionPingGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BotSessionApi - object-oriented interface
 */
export class BotSessionApi extends BaseAPI {
    /**
     * 
     * @summary Get active bot sessions.
     * @param {string} [computer] Optional computer name filter
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiBotSessionActiveGet(computer?: string, options?: RawAxiosRequestConfig) {
        return BotSessionApiFp(this.configuration).apiBotSessionActiveGet(computer, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Mark inactive sessions as stopped (background job endpoint).
     * @param {number} [inactivityMinutes] Minutes of inactivity before marking as stopped
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiBotSessionCleanupInactivePost(inactivityMinutes?: number, options?: RawAxiosRequestConfig) {
        return BotSessionApiFp(this.configuration).apiBotSessionCleanupInactivePost(inactivityMinutes, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Event Types:  - START: Bot session started (creates PC_Start record)  - STOP: Bot session ended (updates PC_Start, creates Stats and Stats_Margine)  - HEARTBEAT: Periodic update (updates session data, creates Stats_Margine snapshot)    Example START request:  ```json  {    \"eventType\": \"START\",    \"computer\": \"BOT-PC-01\",    \"userId\": 1,    \"botVersion\": \"2.5.3\",    \"balance\": 1000.00,    \"reason\": \"Manual\"  }  ```    Example STOP request:  ```json  {    \"eventType\": \"STOP\",    \"computer\": \"BOT-PC-01\",    \"userId\": 1,    \"balance\": 1250.00,    \"margine\": 250.00,    \"reason\": \"Target reached\",    \"totalHands\": 150,    \"totalWins\": 75,    \"totalLosses\": 70,    \"totalTies\": 5,    \"maxProfit\": 280.00,    \"maxDrawdown\": -50.00  }  ```
     * @summary Process a bot session event (START, STOP, HEARTBEAT).
     * @param {BotSessionEventRequest} [botSessionEventRequest] Session event data
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiBotSessionEventPost(botSessionEventRequest?: BotSessionEventRequest, options?: RawAxiosRequestConfig) {
        return BotSessionApiFp(this.configuration).apiBotSessionEventPost(botSessionEventRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Quick ping to verify the service is running.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiBotSessionPingGet(options?: RawAxiosRequestConfig) {
        return BotSessionApiFp(this.configuration).apiBotSessionPingGet(options).then((request) => request(this.axios, this.basePath));
    }
}

