/* tslint:disable */
/* eslint-disable */
/**
 * BotDashboard API
 * API per la gestione del Bot Dashboard con telemetria, comandi e statistiche real-time
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Configuration } from '../models';
// @ts-ignore
import type { CreateConfigurationRequest } from '../models';
// @ts-ignore
import type { ProblemDetails } from '../models';
// @ts-ignore
import type { UpdateConfigurationRequest } from '../models';
/**
 * ConfigurationApi - axios parameter creator
 */
export const ConfigurationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Gets all configurations.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConfigurationGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Configuration`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes a configuration.
         * @param {string} id The configuration identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConfigurationIdDelete: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiConfigurationIdDelete', 'id', id)
            const localVarPath = `/api/Configuration/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates an existing configuration.
         * @param {string} id The configuration identifier.
         * @param {UpdateConfigurationRequest} [updateConfigurationRequest] The update configuration request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConfigurationIdPut: async (id: string, updateConfigurationRequest?: UpdateConfigurationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiConfigurationIdPut', 'id', id)
            const localVarPath = `/api/Configuration/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateConfigurationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets a configuration by its identifier.
         * @param {string} k 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConfigurationKGet: async (k: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'k' is not null or undefined
            assertParamExists('apiConfigurationKGet', 'k', k)
            const localVarPath = `/api/Configuration/{k}`
                .replace(`{${"k"}}`, encodeURIComponent(String(k)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates a new configuration.
         * @param {CreateConfigurationRequest} [createConfigurationRequest] The create configuration request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConfigurationPost: async (createConfigurationRequest?: CreateConfigurationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Configuration`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createConfigurationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ConfigurationApi - functional programming interface
 */
export const ConfigurationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ConfigurationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Gets all configurations.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiConfigurationGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Configuration>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiConfigurationGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConfigurationApi.apiConfigurationGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Deletes a configuration.
         * @param {string} id The configuration identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiConfigurationIdDelete(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiConfigurationIdDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConfigurationApi.apiConfigurationIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Updates an existing configuration.
         * @param {string} id The configuration identifier.
         * @param {UpdateConfigurationRequest} [updateConfigurationRequest] The update configuration request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiConfigurationIdPut(id: string, updateConfigurationRequest?: UpdateConfigurationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiConfigurationIdPut(id, updateConfigurationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConfigurationApi.apiConfigurationIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Gets a configuration by its identifier.
         * @param {string} k 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiConfigurationKGet(k: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Configuration>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiConfigurationKGet(k, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConfigurationApi.apiConfigurationKGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Creates a new configuration.
         * @param {CreateConfigurationRequest} [createConfigurationRequest] The create configuration request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiConfigurationPost(createConfigurationRequest?: CreateConfigurationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Configuration>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiConfigurationPost(createConfigurationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConfigurationApi.apiConfigurationPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ConfigurationApi - factory interface
 */
export const ConfigurationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ConfigurationApiFp(configuration)
    return {
        /**
         * 
         * @summary Gets all configurations.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConfigurationGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<Configuration>> {
            return localVarFp.apiConfigurationGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes a configuration.
         * @param {string} id The configuration identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConfigurationIdDelete(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiConfigurationIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates an existing configuration.
         * @param {string} id The configuration identifier.
         * @param {UpdateConfigurationRequest} [updateConfigurationRequest] The update configuration request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConfigurationIdPut(id: string, updateConfigurationRequest?: UpdateConfigurationRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiConfigurationIdPut(id, updateConfigurationRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets a configuration by its identifier.
         * @param {string} k 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConfigurationKGet(k: string, options?: RawAxiosRequestConfig): AxiosPromise<Configuration> {
            return localVarFp.apiConfigurationKGet(k, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates a new configuration.
         * @param {CreateConfigurationRequest} [createConfigurationRequest] The create configuration request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiConfigurationPost(createConfigurationRequest?: CreateConfigurationRequest, options?: RawAxiosRequestConfig): AxiosPromise<Configuration> {
            return localVarFp.apiConfigurationPost(createConfigurationRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ConfigurationApi - object-oriented interface
 */
export class ConfigurationApi extends BaseAPI {
    /**
     * 
     * @summary Gets all configurations.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiConfigurationGet(options?: RawAxiosRequestConfig) {
        return ConfigurationApiFp(this.configuration).apiConfigurationGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Deletes a configuration.
     * @param {string} id The configuration identifier.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiConfigurationIdDelete(id: string, options?: RawAxiosRequestConfig) {
        return ConfigurationApiFp(this.configuration).apiConfigurationIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Updates an existing configuration.
     * @param {string} id The configuration identifier.
     * @param {UpdateConfigurationRequest} [updateConfigurationRequest] The update configuration request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiConfigurationIdPut(id: string, updateConfigurationRequest?: UpdateConfigurationRequest, options?: RawAxiosRequestConfig) {
        return ConfigurationApiFp(this.configuration).apiConfigurationIdPut(id, updateConfigurationRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets a configuration by its identifier.
     * @param {string} k 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiConfigurationKGet(k: string, options?: RawAxiosRequestConfig) {
        return ConfigurationApiFp(this.configuration).apiConfigurationKGet(k, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Creates a new configuration.
     * @param {CreateConfigurationRequest} [createConfigurationRequest] The create configuration request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiConfigurationPost(createConfigurationRequest?: CreateConfigurationRequest, options?: RawAxiosRequestConfig) {
        return ConfigurationApiFp(this.configuration).apiConfigurationPost(createConfigurationRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

