/* tslint:disable */
/* eslint-disable */
/**
 * BotDashboard API
 * API per la gestione del Bot Dashboard con telemetria, comandi e statistiche real-time
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ChartDataPoint } from '../models';
// @ts-ignore
import type { PcCurrentStatus } from '../models';
/**
 * DashboardApi - axios parameter creator
 */
export const DashboardApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary POST /api/dashboard/emergency-stop  Resetta le tabelle Value e PcCurrentStatus
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDashboardEmergencyStopPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Dashboard/emergency-stop`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary GET /api/dashboard/margini-chart  Restituisce i punti del grafico dei margini (solo quando cambiano)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDashboardMarginiChartGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Dashboard/margini-chart`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary GET /api/dashboard/pc-current-status  Restituisce lo stato corrente di tutti i PC
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDashboardPcCurrentStatusGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Dashboard/pc-current-status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary POST /api/dashboard/reset-tables  Resetta le tabelle Value e PcCurrentStatus
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDashboardResetTablesPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Dashboard/reset-tables`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DashboardApi - functional programming interface
 */
export const DashboardApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DashboardApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary POST /api/dashboard/emergency-stop  Resetta le tabelle Value e PcCurrentStatus
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDashboardEmergencyStopPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiDashboardEmergencyStopPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DashboardApi.apiDashboardEmergencyStopPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary GET /api/dashboard/margini-chart  Restituisce i punti del grafico dei margini (solo quando cambiano)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDashboardMarginiChartGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ChartDataPoint>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiDashboardMarginiChartGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DashboardApi.apiDashboardMarginiChartGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary GET /api/dashboard/pc-current-status  Restituisce lo stato corrente di tutti i PC
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDashboardPcCurrentStatusGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PcCurrentStatus>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiDashboardPcCurrentStatusGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DashboardApi.apiDashboardPcCurrentStatusGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary POST /api/dashboard/reset-tables  Resetta le tabelle Value e PcCurrentStatus
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDashboardResetTablesPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiDashboardResetTablesPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DashboardApi.apiDashboardResetTablesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DashboardApi - factory interface
 */
export const DashboardApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DashboardApiFp(configuration)
    return {
        /**
         * 
         * @summary POST /api/dashboard/emergency-stop  Resetta le tabelle Value e PcCurrentStatus
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDashboardEmergencyStopPost(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiDashboardEmergencyStopPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary GET /api/dashboard/margini-chart  Restituisce i punti del grafico dei margini (solo quando cambiano)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDashboardMarginiChartGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<ChartDataPoint>> {
            return localVarFp.apiDashboardMarginiChartGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary GET /api/dashboard/pc-current-status  Restituisce lo stato corrente di tutti i PC
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDashboardPcCurrentStatusGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<PcCurrentStatus>> {
            return localVarFp.apiDashboardPcCurrentStatusGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary POST /api/dashboard/reset-tables  Resetta le tabelle Value e PcCurrentStatus
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDashboardResetTablesPost(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiDashboardResetTablesPost(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DashboardApi - object-oriented interface
 */
export class DashboardApi extends BaseAPI {
    /**
     * 
     * @summary POST /api/dashboard/emergency-stop  Resetta le tabelle Value e PcCurrentStatus
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiDashboardEmergencyStopPost(options?: RawAxiosRequestConfig) {
        return DashboardApiFp(this.configuration).apiDashboardEmergencyStopPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary GET /api/dashboard/margini-chart  Restituisce i punti del grafico dei margini (solo quando cambiano)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiDashboardMarginiChartGet(options?: RawAxiosRequestConfig) {
        return DashboardApiFp(this.configuration).apiDashboardMarginiChartGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary GET /api/dashboard/pc-current-status  Restituisce lo stato corrente di tutti i PC
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiDashboardPcCurrentStatusGet(options?: RawAxiosRequestConfig) {
        return DashboardApiFp(this.configuration).apiDashboardPcCurrentStatusGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary POST /api/dashboard/reset-tables  Resetta le tabelle Value e PcCurrentStatus
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiDashboardResetTablesPost(options?: RawAxiosRequestConfig) {
        return DashboardApiFp(this.configuration).apiDashboardResetTablesPost(options).then((request) => request(this.axios, this.basePath));
    }
}

