/* tslint:disable */
/* eslint-disable */
/**
 * BotDashboard API
 * API per la gestione del Bot Dashboard con telemetria, comandi e statistiche real-time
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateDeviceRequest } from '../models';
// @ts-ignore
import type { DeviceApiResponse } from '../models';
// @ts-ignore
import type { DeviceIEnumerableApiResponse } from '../models';
// @ts-ignore
import type { ObjectApiResponse } from '../models';
// @ts-ignore
import type { UpdateDeviceRequest } from '../models';
/**
 * DeviceApi - axios parameter creator
 */
export const DeviceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Gets all devices.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDeviceGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Device`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes a device.
         * @param {number} id The device identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDeviceIdDelete: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiDeviceIdDelete', 'id', id)
            const localVarPath = `/api/Device/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets a device by its identifier.
         * @param {number} id The device identifier (PC name).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDeviceIdGet: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiDeviceIdGet', 'id', id)
            const localVarPath = `/api/Device/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Updates an existing device.
         * @param {number} id The device identifier.
         * @param {UpdateDeviceRequest} [updateDeviceRequest] The update device request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDeviceIdPut: async (id: number, updateDeviceRequest?: UpdateDeviceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiDeviceIdPut', 'id', id)
            const localVarPath = `/api/Device/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateDeviceRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates a new device.
         * @param {CreateDeviceRequest} [createDeviceRequest] The create device request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDevicePost: async (createDeviceRequest?: CreateDeviceRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Device`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createDeviceRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DeviceApi - functional programming interface
 */
export const DeviceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DeviceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Gets all devices.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDeviceGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeviceIEnumerableApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiDeviceGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeviceApi.apiDeviceGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Deletes a device.
         * @param {number} id The device identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDeviceIdDelete(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ObjectApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiDeviceIdDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeviceApi.apiDeviceIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Gets a device by its identifier.
         * @param {number} id The device identifier (PC name).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDeviceIdGet(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeviceApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiDeviceIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeviceApi.apiDeviceIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Updates an existing device.
         * @param {number} id The device identifier.
         * @param {UpdateDeviceRequest} [updateDeviceRequest] The update device request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDeviceIdPut(id: number, updateDeviceRequest?: UpdateDeviceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeviceApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiDeviceIdPut(id, updateDeviceRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeviceApi.apiDeviceIdPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Creates a new device.
         * @param {CreateDeviceRequest} [createDeviceRequest] The create device request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiDevicePost(createDeviceRequest?: CreateDeviceRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeviceApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiDevicePost(createDeviceRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeviceApi.apiDevicePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DeviceApi - factory interface
 */
export const DeviceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DeviceApiFp(configuration)
    return {
        /**
         * 
         * @summary Gets all devices.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDeviceGet(options?: RawAxiosRequestConfig): AxiosPromise<DeviceIEnumerableApiResponse> {
            return localVarFp.apiDeviceGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes a device.
         * @param {number} id The device identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDeviceIdDelete(id: number, options?: RawAxiosRequestConfig): AxiosPromise<ObjectApiResponse> {
            return localVarFp.apiDeviceIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets a device by its identifier.
         * @param {number} id The device identifier (PC name).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDeviceIdGet(id: number, options?: RawAxiosRequestConfig): AxiosPromise<DeviceApiResponse> {
            return localVarFp.apiDeviceIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Updates an existing device.
         * @param {number} id The device identifier.
         * @param {UpdateDeviceRequest} [updateDeviceRequest] The update device request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDeviceIdPut(id: number, updateDeviceRequest?: UpdateDeviceRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeviceApiResponse> {
            return localVarFp.apiDeviceIdPut(id, updateDeviceRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates a new device.
         * @param {CreateDeviceRequest} [createDeviceRequest] The create device request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiDevicePost(createDeviceRequest?: CreateDeviceRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeviceApiResponse> {
            return localVarFp.apiDevicePost(createDeviceRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DeviceApi - object-oriented interface
 */
export class DeviceApi extends BaseAPI {
    /**
     * 
     * @summary Gets all devices.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiDeviceGet(options?: RawAxiosRequestConfig) {
        return DeviceApiFp(this.configuration).apiDeviceGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Deletes a device.
     * @param {number} id The device identifier.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiDeviceIdDelete(id: number, options?: RawAxiosRequestConfig) {
        return DeviceApiFp(this.configuration).apiDeviceIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets a device by its identifier.
     * @param {number} id The device identifier (PC name).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiDeviceIdGet(id: number, options?: RawAxiosRequestConfig) {
        return DeviceApiFp(this.configuration).apiDeviceIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Updates an existing device.
     * @param {number} id The device identifier.
     * @param {UpdateDeviceRequest} [updateDeviceRequest] The update device request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiDeviceIdPut(id: number, updateDeviceRequest?: UpdateDeviceRequest, options?: RawAxiosRequestConfig) {
        return DeviceApiFp(this.configuration).apiDeviceIdPut(id, updateDeviceRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Creates a new device.
     * @param {CreateDeviceRequest} [createDeviceRequest] The create device request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiDevicePost(createDeviceRequest?: CreateDeviceRequest, options?: RawAxiosRequestConfig) {
        return DeviceApiFp(this.configuration).apiDevicePost(createDeviceRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

