/* tslint:disable */
/* eslint-disable */
/**
 * BotDashboard API
 * API per la gestione del Bot Dashboard con telemetria, comandi e statistiche real-time
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * LegacyBotApi - axios parameter creator
 */
export const LegacyBotApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Endpoint /api/legacybot/sync - Replica esatta di index.aspx.cs  Query params: username, password, COMPUTER, TAVOLO, MARGINE, COLPO_MARTINGALA, PBT, MAZZO, TEMPO  Additional params: ACCOUNT, SALDO_INIZIALE, SALDO_ISTANTANEO, VINCITA, VALORE_GIOCATO, AVVIO  Returns: \"0\" (nessuna azione), \"1\" (Stop PC), \"2\" (Azzera Martingala), \"3\" (Start PC), \"9\" (Errore)
         * @param {string} [username] 
         * @param {string} [password] 
         * @param {string} [cOMPUTER] 
         * @param {string} [tAVOLO] 
         * @param {string} [mARGINE] 
         * @param {string} [cOLPOMARTINGALA] 
         * @param {string} [pBT] 
         * @param {string} [mAZZO] 
         * @param {string} [tEMPO] 
         * @param {string} [aCCOUNT] 
         * @param {string} [sALDOINIZIALE] 
         * @param {string} [sALDOISTANTANEO] 
         * @param {string} [vINCITA] 
         * @param {string} [vALOREGIOCATO] 
         * @param {string} [aVVIO] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLegacyBotSyncGet: async (username?: string, password?: string, cOMPUTER?: string, tAVOLO?: string, mARGINE?: string, cOLPOMARTINGALA?: string, pBT?: string, mAZZO?: string, tEMPO?: string, aCCOUNT?: string, sALDOINIZIALE?: string, sALDOISTANTANEO?: string, vINCITA?: string, vALOREGIOCATO?: string, aVVIO?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/LegacyBot/sync`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (username !== undefined) {
                localVarQueryParameter['username'] = username;
            }

            if (password !== undefined) {
                localVarQueryParameter['password'] = password;
            }

            if (cOMPUTER !== undefined) {
                localVarQueryParameter['COMPUTER'] = cOMPUTER;
            }

            if (tAVOLO !== undefined) {
                localVarQueryParameter['TAVOLO'] = tAVOLO;
            }

            if (mARGINE !== undefined) {
                localVarQueryParameter['MARGINE'] = mARGINE;
            }

            if (cOLPOMARTINGALA !== undefined) {
                localVarQueryParameter['COLPO_MARTINGALA'] = cOLPOMARTINGALA;
            }

            if (pBT !== undefined) {
                localVarQueryParameter['PBT'] = pBT;
            }

            if (mAZZO !== undefined) {
                localVarQueryParameter['MAZZO'] = mAZZO;
            }

            if (tEMPO !== undefined) {
                localVarQueryParameter['TEMPO'] = tEMPO;
            }

            if (aCCOUNT !== undefined) {
                localVarQueryParameter['ACCOUNT'] = aCCOUNT;
            }

            if (sALDOINIZIALE !== undefined) {
                localVarQueryParameter['SALDO_INIZIALE'] = sALDOINIZIALE;
            }

            if (sALDOISTANTANEO !== undefined) {
                localVarQueryParameter['SALDO_ISTANTANEO'] = sALDOISTANTANEO;
            }

            if (vINCITA !== undefined) {
                localVarQueryParameter['VINCITA'] = vINCITA;
            }

            if (vALOREGIOCATO !== undefined) {
                localVarQueryParameter['VALORE_GIOCATO'] = vALOREGIOCATO;
            }

            if (aVVIO !== undefined) {
                localVarQueryParameter['AVVIO'] = aVVIO;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LegacyBotApi - functional programming interface
 */
export const LegacyBotApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LegacyBotApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Endpoint /api/legacybot/sync - Replica esatta di index.aspx.cs  Query params: username, password, COMPUTER, TAVOLO, MARGINE, COLPO_MARTINGALA, PBT, MAZZO, TEMPO  Additional params: ACCOUNT, SALDO_INIZIALE, SALDO_ISTANTANEO, VINCITA, VALORE_GIOCATO, AVVIO  Returns: \"0\" (nessuna azione), \"1\" (Stop PC), \"2\" (Azzera Martingala), \"3\" (Start PC), \"9\" (Errore)
         * @param {string} [username] 
         * @param {string} [password] 
         * @param {string} [cOMPUTER] 
         * @param {string} [tAVOLO] 
         * @param {string} [mARGINE] 
         * @param {string} [cOLPOMARTINGALA] 
         * @param {string} [pBT] 
         * @param {string} [mAZZO] 
         * @param {string} [tEMPO] 
         * @param {string} [aCCOUNT] 
         * @param {string} [sALDOINIZIALE] 
         * @param {string} [sALDOISTANTANEO] 
         * @param {string} [vINCITA] 
         * @param {string} [vALOREGIOCATO] 
         * @param {string} [aVVIO] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLegacyBotSyncGet(username?: string, password?: string, cOMPUTER?: string, tAVOLO?: string, mARGINE?: string, cOLPOMARTINGALA?: string, pBT?: string, mAZZO?: string, tEMPO?: string, aCCOUNT?: string, sALDOINIZIALE?: string, sALDOISTANTANEO?: string, vINCITA?: string, vALOREGIOCATO?: string, aVVIO?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiLegacyBotSyncGet(username, password, cOMPUTER, tAVOLO, mARGINE, cOLPOMARTINGALA, pBT, mAZZO, tEMPO, aCCOUNT, sALDOINIZIALE, sALDOISTANTANEO, vINCITA, vALOREGIOCATO, aVVIO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LegacyBotApi.apiLegacyBotSyncGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LegacyBotApi - factory interface
 */
export const LegacyBotApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LegacyBotApiFp(configuration)
    return {
        /**
         * 
         * @summary Endpoint /api/legacybot/sync - Replica esatta di index.aspx.cs  Query params: username, password, COMPUTER, TAVOLO, MARGINE, COLPO_MARTINGALA, PBT, MAZZO, TEMPO  Additional params: ACCOUNT, SALDO_INIZIALE, SALDO_ISTANTANEO, VINCITA, VALORE_GIOCATO, AVVIO  Returns: \"0\" (nessuna azione), \"1\" (Stop PC), \"2\" (Azzera Martingala), \"3\" (Start PC), \"9\" (Errore)
         * @param {string} [username] 
         * @param {string} [password] 
         * @param {string} [cOMPUTER] 
         * @param {string} [tAVOLO] 
         * @param {string} [mARGINE] 
         * @param {string} [cOLPOMARTINGALA] 
         * @param {string} [pBT] 
         * @param {string} [mAZZO] 
         * @param {string} [tEMPO] 
         * @param {string} [aCCOUNT] 
         * @param {string} [sALDOINIZIALE] 
         * @param {string} [sALDOISTANTANEO] 
         * @param {string} [vINCITA] 
         * @param {string} [vALOREGIOCATO] 
         * @param {string} [aVVIO] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLegacyBotSyncGet(username?: string, password?: string, cOMPUTER?: string, tAVOLO?: string, mARGINE?: string, cOLPOMARTINGALA?: string, pBT?: string, mAZZO?: string, tEMPO?: string, aCCOUNT?: string, sALDOINIZIALE?: string, sALDOISTANTANEO?: string, vINCITA?: string, vALOREGIOCATO?: string, aVVIO?: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiLegacyBotSyncGet(username, password, cOMPUTER, tAVOLO, mARGINE, cOLPOMARTINGALA, pBT, mAZZO, tEMPO, aCCOUNT, sALDOINIZIALE, sALDOISTANTANEO, vINCITA, vALOREGIOCATO, aVVIO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LegacyBotApi - object-oriented interface
 */
export class LegacyBotApi extends BaseAPI {
    /**
     * 
     * @summary Endpoint /api/legacybot/sync - Replica esatta di index.aspx.cs  Query params: username, password, COMPUTER, TAVOLO, MARGINE, COLPO_MARTINGALA, PBT, MAZZO, TEMPO  Additional params: ACCOUNT, SALDO_INIZIALE, SALDO_ISTANTANEO, VINCITA, VALORE_GIOCATO, AVVIO  Returns: \"0\" (nessuna azione), \"1\" (Stop PC), \"2\" (Azzera Martingala), \"3\" (Start PC), \"9\" (Errore)
     * @param {string} [username] 
     * @param {string} [password] 
     * @param {string} [cOMPUTER] 
     * @param {string} [tAVOLO] 
     * @param {string} [mARGINE] 
     * @param {string} [cOLPOMARTINGALA] 
     * @param {string} [pBT] 
     * @param {string} [mAZZO] 
     * @param {string} [tEMPO] 
     * @param {string} [aCCOUNT] 
     * @param {string} [sALDOINIZIALE] 
     * @param {string} [sALDOISTANTANEO] 
     * @param {string} [vINCITA] 
     * @param {string} [vALOREGIOCATO] 
     * @param {string} [aVVIO] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiLegacyBotSyncGet(username?: string, password?: string, cOMPUTER?: string, tAVOLO?: string, mARGINE?: string, cOLPOMARTINGALA?: string, pBT?: string, mAZZO?: string, tEMPO?: string, aCCOUNT?: string, sALDOINIZIALE?: string, sALDOISTANTANEO?: string, vINCITA?: string, vALOREGIOCATO?: string, aVVIO?: string, options?: RawAxiosRequestConfig) {
        return LegacyBotApiFp(this.configuration).apiLegacyBotSyncGet(username, password, cOMPUTER, tAVOLO, mARGINE, cOLPOMARTINGALA, pBT, mAZZO, tEMPO, aCCOUNT, sALDOINIZIALE, sALDOISTANTANEO, vINCITA, vALOREGIOCATO, aVVIO, options).then((request) => request(this.axios, this.basePath));
    }
}

