/* tslint:disable */
/* eslint-disable */
/**
 * BotDashboard API
 * API per la gestione del Bot Dashboard con telemetria, comandi e statistiche real-time
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { PagedApiLogResult } from '../models';
/**
 * LogApi - axios parameter creator
 */
export const LogApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Deletes ApiLogs matching the given filters.
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {string} [category] 
         * @param {number} [action] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLogDelete: async (from?: string, to?: string, category?: string, action?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Log`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }

            if (category !== undefined) {
                localVarQueryParameter['category'] = category;
            }

            if (action !== undefined) {
                localVarQueryParameter['action'] = action;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets ApiLogs with optional filters for CreatedAt (range), Category, and Action.
         * @param {string} [from] Start of CreatedAt range (inclusive, optional).
         * @param {string} [to] End of CreatedAt range (inclusive, optional).
         * @param {string} [category] Category filter (optional).
         * @param {number} [action] Action filter (optional).
         * @param {string} [description] 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLogGet: async (from?: string, to?: string, category?: string, action?: number, description?: string, page?: number, pageSize?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Log`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (from !== undefined) {
                localVarQueryParameter['from'] = (from as any instanceof Date) ?
                    (from as any).toISOString() :
                    from;
            }

            if (to !== undefined) {
                localVarQueryParameter['to'] = (to as any instanceof Date) ?
                    (to as any).toISOString() :
                    to;
            }

            if (category !== undefined) {
                localVarQueryParameter['category'] = category;
            }

            if (action !== undefined) {
                localVarQueryParameter['action'] = action;
            }

            if (description !== undefined) {
                localVarQueryParameter['description'] = description;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LogApi - functional programming interface
 */
export const LogApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LogApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Deletes ApiLogs matching the given filters.
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {string} [category] 
         * @param {number} [action] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLogDelete(from?: string, to?: string, category?: string, action?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiLogDelete(from, to, category, action, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LogApi.apiLogDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Gets ApiLogs with optional filters for CreatedAt (range), Category, and Action.
         * @param {string} [from] Start of CreatedAt range (inclusive, optional).
         * @param {string} [to] End of CreatedAt range (inclusive, optional).
         * @param {string} [category] Category filter (optional).
         * @param {number} [action] Action filter (optional).
         * @param {string} [description] 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiLogGet(from?: string, to?: string, category?: string, action?: number, description?: string, page?: number, pageSize?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PagedApiLogResult>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiLogGet(from, to, category, action, description, page, pageSize, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LogApi.apiLogGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LogApi - factory interface
 */
export const LogApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LogApiFp(configuration)
    return {
        /**
         * 
         * @summary Deletes ApiLogs matching the given filters.
         * @param {string} [from] 
         * @param {string} [to] 
         * @param {string} [category] 
         * @param {number} [action] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLogDelete(from?: string, to?: string, category?: string, action?: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiLogDelete(from, to, category, action, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets ApiLogs with optional filters for CreatedAt (range), Category, and Action.
         * @param {string} [from] Start of CreatedAt range (inclusive, optional).
         * @param {string} [to] End of CreatedAt range (inclusive, optional).
         * @param {string} [category] Category filter (optional).
         * @param {number} [action] Action filter (optional).
         * @param {string} [description] 
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiLogGet(from?: string, to?: string, category?: string, action?: number, description?: string, page?: number, pageSize?: number, options?: RawAxiosRequestConfig): AxiosPromise<PagedApiLogResult> {
            return localVarFp.apiLogGet(from, to, category, action, description, page, pageSize, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LogApi - object-oriented interface
 */
export class LogApi extends BaseAPI {
    /**
     * 
     * @summary Deletes ApiLogs matching the given filters.
     * @param {string} [from] 
     * @param {string} [to] 
     * @param {string} [category] 
     * @param {number} [action] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiLogDelete(from?: string, to?: string, category?: string, action?: number, options?: RawAxiosRequestConfig) {
        return LogApiFp(this.configuration).apiLogDelete(from, to, category, action, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets ApiLogs with optional filters for CreatedAt (range), Category, and Action.
     * @param {string} [from] Start of CreatedAt range (inclusive, optional).
     * @param {string} [to] End of CreatedAt range (inclusive, optional).
     * @param {string} [category] Category filter (optional).
     * @param {number} [action] Action filter (optional).
     * @param {string} [description] 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiLogGet(from?: string, to?: string, category?: string, action?: number, description?: string, page?: number, pageSize?: number, options?: RawAxiosRequestConfig) {
        return LogApiFp(this.configuration).apiLogGet(from, to, category, action, description, page, pageSize, options).then((request) => request(this.axios, this.basePath));
    }
}

