/* tslint:disable */
/* eslint-disable */
/**
 * BotDashboard API
 * API per la gestione del Bot Dashboard con telemetria, comandi e statistiche real-time
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AssignPermissionRequest } from '../models';
// @ts-ignore
import type { AssignRoleRequest } from '../models';
// @ts-ignore
import type { CreateUserRequest } from '../models';
// @ts-ignore
import type { ObjectApiResponse } from '../models';
// @ts-ignore
import type { StringIEnumerableApiResponse } from '../models';
// @ts-ignore
import type { UserApiResponse } from '../models';
// @ts-ignore
import type { UserIEnumerableApiResponse } from '../models';
// @ts-ignore
import type { UserRolesAndPermissionsResponseApiResponse } from '../models';
/**
 * UserApi - axios parameter creator
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Gets all available permissions in the system from database (Admin only).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserAvailablePermissionsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/User/available-permissions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets all available roles in the system from database (Admin only).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserAvailableRolesGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/User/available-roles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets all users (Admin only).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/User`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Deletes a user (Admin only).
         * @param {string} id The user identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdDelete: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiUserIdDelete', 'id', id)
            const localVarPath = `/api/User/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets a user by ID (Authenticated users can see their own profile, Admin can see all).
         * @param {string} id The user identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiUserIdGet', 'id', id)
            const localVarPath = `/api/User/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Removes a permission from a user (Admin only).
         * @param {string} id The user identifier.
         * @param {string} permission The permission to remove.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdPermissionsPermissionDelete: async (id: string, permission: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiUserIdPermissionsPermissionDelete', 'id', id)
            // verify required parameter 'permission' is not null or undefined
            assertParamExists('apiUserIdPermissionsPermissionDelete', 'permission', permission)
            const localVarPath = `/api/User/{id}/permissions/{permission}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"permission"}}`, encodeURIComponent(String(permission)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Assigns a permission to a user (Admin only).
         * @param {string} id The user identifier.
         * @param {AssignPermissionRequest} [assignPermissionRequest] The permission assignment request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdPermissionsPost: async (id: string, assignPermissionRequest?: AssignPermissionRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiUserIdPermissionsPost', 'id', id)
            const localVarPath = `/api/User/{id}/permissions`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(assignPermissionRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Gets all roles and permissions for a user (Admin only).
         * @param {string} id The user identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdRolesAndPermissionsGet: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiUserIdRolesAndPermissionsGet', 'id', id)
            const localVarPath = `/api/User/{id}/roles-and-permissions`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Assigns a role to a user (Admin only).
         * @param {string} id The user identifier.
         * @param {AssignRoleRequest} [assignRoleRequest] The role assignment request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdRolesPost: async (id: string, assignRoleRequest?: AssignRoleRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiUserIdRolesPost', 'id', id)
            const localVarPath = `/api/User/{id}/roles`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(assignRoleRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Removes a role from a user (Admin only).
         * @param {string} id The user identifier.
         * @param {string} roleName The role name to remove.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdRolesRoleNameDelete: async (id: string, roleName: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiUserIdRolesRoleNameDelete', 'id', id)
            // verify required parameter 'roleName' is not null or undefined
            assertParamExists('apiUserIdRolesRoleNameDelete', 'roleName', roleName)
            const localVarPath = `/api/User/{id}/roles/{roleName}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"roleName"}}`, encodeURIComponent(String(roleName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Creates a new user (Admin only).
         * @param {string} [roleName] Optional role name (Admin, User, BotOperator). Default is based on IsAdmin flag.
         * @param {CreateUserRequest} [createUserRequest] The create user request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserPost: async (roleName?: string, createUserRequest?: CreateUserRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/User`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (roleName !== undefined) {
                localVarQueryParameter['roleName'] = roleName;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createUserRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Gets all available permissions in the system from database (Admin only).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserAvailablePermissionsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ObjectApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserAvailablePermissionsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.apiUserAvailablePermissionsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Gets all available roles in the system from database (Admin only).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserAvailableRolesGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StringIEnumerableApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserAvailableRolesGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.apiUserAvailableRolesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Gets all users (Admin only).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserIEnumerableApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.apiUserGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Deletes a user (Admin only).
         * @param {string} id The user identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserIdDelete(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ObjectApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserIdDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.apiUserIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Gets a user by ID (Authenticated users can see their own profile, Admin can see all).
         * @param {string} id The user identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserIdGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.apiUserIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Removes a permission from a user (Admin only).
         * @param {string} id The user identifier.
         * @param {string} permission The permission to remove.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserIdPermissionsPermissionDelete(id: string, permission: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ObjectApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserIdPermissionsPermissionDelete(id, permission, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.apiUserIdPermissionsPermissionDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Assigns a permission to a user (Admin only).
         * @param {string} id The user identifier.
         * @param {AssignPermissionRequest} [assignPermissionRequest] The permission assignment request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserIdPermissionsPost(id: string, assignPermissionRequest?: AssignPermissionRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ObjectApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserIdPermissionsPost(id, assignPermissionRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.apiUserIdPermissionsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Gets all roles and permissions for a user (Admin only).
         * @param {string} id The user identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserIdRolesAndPermissionsGet(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserRolesAndPermissionsResponseApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserIdRolesAndPermissionsGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.apiUserIdRolesAndPermissionsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Assigns a role to a user (Admin only).
         * @param {string} id The user identifier.
         * @param {AssignRoleRequest} [assignRoleRequest] The role assignment request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserIdRolesPost(id: string, assignRoleRequest?: AssignRoleRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ObjectApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserIdRolesPost(id, assignRoleRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.apiUserIdRolesPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Removes a role from a user (Admin only).
         * @param {string} id The user identifier.
         * @param {string} roleName The role name to remove.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserIdRolesRoleNameDelete(id: string, roleName: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ObjectApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserIdRolesRoleNameDelete(id, roleName, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.apiUserIdRolesRoleNameDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Creates a new user (Admin only).
         * @param {string} [roleName] Optional role name (Admin, User, BotOperator). Default is based on IsAdmin flag.
         * @param {CreateUserRequest} [createUserRequest] The create user request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserPost(roleName?: string, createUserRequest?: CreateUserRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserApiResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserPost(roleName, createUserRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.apiUserPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 
         * @summary Gets all available permissions in the system from database (Admin only).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserAvailablePermissionsGet(options?: RawAxiosRequestConfig): AxiosPromise<ObjectApiResponse> {
            return localVarFp.apiUserAvailablePermissionsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets all available roles in the system from database (Admin only).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserAvailableRolesGet(options?: RawAxiosRequestConfig): AxiosPromise<StringIEnumerableApiResponse> {
            return localVarFp.apiUserAvailableRolesGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets all users (Admin only).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserGet(options?: RawAxiosRequestConfig): AxiosPromise<UserIEnumerableApiResponse> {
            return localVarFp.apiUserGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Deletes a user (Admin only).
         * @param {string} id The user identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdDelete(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ObjectApiResponse> {
            return localVarFp.apiUserIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets a user by ID (Authenticated users can see their own profile, Admin can see all).
         * @param {string} id The user identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<UserApiResponse> {
            return localVarFp.apiUserIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Removes a permission from a user (Admin only).
         * @param {string} id The user identifier.
         * @param {string} permission The permission to remove.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdPermissionsPermissionDelete(id: string, permission: string, options?: RawAxiosRequestConfig): AxiosPromise<ObjectApiResponse> {
            return localVarFp.apiUserIdPermissionsPermissionDelete(id, permission, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Assigns a permission to a user (Admin only).
         * @param {string} id The user identifier.
         * @param {AssignPermissionRequest} [assignPermissionRequest] The permission assignment request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdPermissionsPost(id: string, assignPermissionRequest?: AssignPermissionRequest, options?: RawAxiosRequestConfig): AxiosPromise<ObjectApiResponse> {
            return localVarFp.apiUserIdPermissionsPost(id, assignPermissionRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Gets all roles and permissions for a user (Admin only).
         * @param {string} id The user identifier.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdRolesAndPermissionsGet(id: string, options?: RawAxiosRequestConfig): AxiosPromise<UserRolesAndPermissionsResponseApiResponse> {
            return localVarFp.apiUserIdRolesAndPermissionsGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Assigns a role to a user (Admin only).
         * @param {string} id The user identifier.
         * @param {AssignRoleRequest} [assignRoleRequest] The role assignment request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdRolesPost(id: string, assignRoleRequest?: AssignRoleRequest, options?: RawAxiosRequestConfig): AxiosPromise<ObjectApiResponse> {
            return localVarFp.apiUserIdRolesPost(id, assignRoleRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Removes a role from a user (Admin only).
         * @param {string} id The user identifier.
         * @param {string} roleName The role name to remove.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserIdRolesRoleNameDelete(id: string, roleName: string, options?: RawAxiosRequestConfig): AxiosPromise<ObjectApiResponse> {
            return localVarFp.apiUserIdRolesRoleNameDelete(id, roleName, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Creates a new user (Admin only).
         * @param {string} [roleName] Optional role name (Admin, User, BotOperator). Default is based on IsAdmin flag.
         * @param {CreateUserRequest} [createUserRequest] The create user request.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserPost(roleName?: string, createUserRequest?: CreateUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserApiResponse> {
            return localVarFp.apiUserPost(roleName, createUserRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 */
export class UserApi extends BaseAPI {
    /**
     * 
     * @summary Gets all available permissions in the system from database (Admin only).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiUserAvailablePermissionsGet(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserAvailablePermissionsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets all available roles in the system from database (Admin only).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiUserAvailableRolesGet(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserAvailableRolesGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets all users (Admin only).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiUserGet(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Deletes a user (Admin only).
     * @param {string} id The user identifier.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiUserIdDelete(id: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets a user by ID (Authenticated users can see their own profile, Admin can see all).
     * @param {string} id The user identifier.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiUserIdGet(id: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Removes a permission from a user (Admin only).
     * @param {string} id The user identifier.
     * @param {string} permission The permission to remove.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiUserIdPermissionsPermissionDelete(id: string, permission: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserIdPermissionsPermissionDelete(id, permission, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Assigns a permission to a user (Admin only).
     * @param {string} id The user identifier.
     * @param {AssignPermissionRequest} [assignPermissionRequest] The permission assignment request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiUserIdPermissionsPost(id: string, assignPermissionRequest?: AssignPermissionRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserIdPermissionsPost(id, assignPermissionRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Gets all roles and permissions for a user (Admin only).
     * @param {string} id The user identifier.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiUserIdRolesAndPermissionsGet(id: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserIdRolesAndPermissionsGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Assigns a role to a user (Admin only).
     * @param {string} id The user identifier.
     * @param {AssignRoleRequest} [assignRoleRequest] The role assignment request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiUserIdRolesPost(id: string, assignRoleRequest?: AssignRoleRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserIdRolesPost(id, assignRoleRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Removes a role from a user (Admin only).
     * @param {string} id The user identifier.
     * @param {string} roleName The role name to remove.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiUserIdRolesRoleNameDelete(id: string, roleName: string, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserIdRolesRoleNameDelete(id, roleName, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Creates a new user (Admin only).
     * @param {string} [roleName] Optional role name (Admin, User, BotOperator). Default is based on IsAdmin flag.
     * @param {CreateUserRequest} [createUserRequest] The create user request.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiUserPost(roleName?: string, createUserRequest?: CreateUserRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserPost(roleName, createUserRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

