/* tslint:disable */
/* eslint-disable */
/**
 * BotDashboard API
 * API per la gestione del Bot Dashboard con telemetria, comandi e statistiche real-time
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface BotSessionEventRequest {
    'eventType': string | null;
    'computer': string | null;
    'userId'?: number;
    'botVersion'?: string | null;
    'balance'?: number | null;
    'reason'?: string | null;
    'margine'?: number | null;
    'tavolo'?: number | null;
    'totalHands'?: number | null;
    'totalWins'?: number | null;
    'totalLosses'?: number | null;
    'totalTies'?: number | null;
    'maxProfit'?: number | null;
    'maxDrawdown'?: number | null;
    'elapsedMinutes'?: number | null;
    'jsonData'?: string | null;
    'notes'?: string | null;
}

