/* tslint:disable */
/* eslint-disable */
/**
 * BotDashboard API
 * API per la gestione del Bot Dashboard con telemetria, comandi e statistiche real-time
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface DashboardRow {
    'account'?: string | null;
    'tavolo'?: number;
    'margine'?: number;
    'mazzo'?: number;
    'colpoMartingala'?: number;
    'colore'?: string | null;
    'allarme'?: string | null;
    'valoreGiocato'?: number;
    'pbt'?: string | null;
    'vincita'?: number;
    'minutiPassati'?: number;
    'ore'?: string | null;
    'levelIndex'?: number | null;
    'stakeUnits'?: number | null;
    'stopAtL5'?: boolean | null;
    'authorizedHeavy'?: boolean | null;
    'reason'?: string | null;
    'hotZone'?: string | null;
    'hotZoneLabel'?: string | null;
    'note'?: string | null;
    'vmLocal20'?: number | null;
    'prediction'?: string | null;
    'signalW10'?: string | null;
    'history'?: string | null;
    'valutazione'?: string | null;
    'jsonState'?: string | null;
}

