/* tslint:disable */
/* eslint-disable */
/**
 * BotDashboard API
 * API per la gestione del Bot Dashboard con telemetria, comandi e statistiche real-time
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Represents dashboard statistics and aggregated data.
 */
export interface DashboardStatistics {
    'totalMargine'?: number;
    'tempoTrascorso'?: string | null;
    'margineMin'?: number;
    'margineMax'?: number;
    'margineAttuale'?: number;
    'totaleRighe'?: number;
}

