/* tslint:disable */
/* eslint-disable */
/**
 * BotDashboard API
 * API per la gestione del Bot Dashboard con telemetria, comandi e statistiche real-time
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Represents a single row in the dashboard table.
 */
export interface DashboardTableRow {
    'minutiPassati'?: string | null;
    'account'?: string | null;
    'tavolo'?: string | null;
    'mazzo'?: string | null;
    'margine'?: number;
    'mediaOra'?: number;
    'valoreGiocato'?: string | null;
    'stato'?: string | null;
    'colore'?: string | null;
    'colpoMartingala'?: string | null;
    'valutazione'?: string | null;
    'reason'?: string | null;
    'prediction'?: string | null;
    'pbt'?: string | null;
    'pbtHistory'?: Array<string> | null;
    'vincita'?: number | null;
    'avvio'?: number | null;
    'accountCasino'?: string | null;
    'saldoIniziale'?: number;
    'saldoIstantaneo'?: number;
    'ore'?: string | null;
}

