/* tslint:disable */
/* eslint-disable */
/**
 * BotDashboard API
 * API per la gestione del Bot Dashboard con telemetria, comandi e statistiche real-time
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChartDataPoint } from './chart-data-point';
// May contain unused imports in some cases
// @ts-ignore
import type { DashboardRow } from './dashboard-row';
// May contain unused imports in some cases
// @ts-ignore
import type { DashboardSummary } from './dashboard-summary';

export interface DashboardDataResponse {
    'rows'?: Array<DashboardRow> | null;
    'chartData'?: Array<ChartDataPoint> | null;
    'summary'?: DashboardSummary;
}

