/* tslint:disable */
/* eslint-disable */
/**
 * BotDashboard API
 * API per la gestione del Bot Dashboard con telemetria, comandi e statistiche real-time
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DashboardResponse } from './dashboard-response';

/**
 * Represents a standardized API response.
 */
export interface DashboardResponseApiResponse {
    /**
     * Gets or sets a value indicating whether the operation was successful.
     */
    'success'?: boolean;
    /**
     * Gets or sets the message describing the result.
     */
    'message'?: string | null;
    'data'?: DashboardResponse;
    /**
     * Gets or sets the list of errors, if any.
     */
    'errors'?: Array<string> | null;
    /**
     * Gets or sets the timestamp of the response.
     */
    'timestamp'?: string;
}

