/* tslint:disable */
/* eslint-disable */
/**
 * BotDashboard API
 * API per la gestione del Bot Dashboard con telemetria, comandi e statistiche real-time
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChartDataPoint } from './chart-data-point';
// May contain unused imports in some cases
// @ts-ignore
import type { DashboardStatistics } from './dashboard-statistics';
// May contain unused imports in some cases
// @ts-ignore
import type { DashboardTableRow } from './dashboard-table-row';

/**
 * Represents a complete dashboard response with tables, chart data, and statistics.
 */
export interface DashboardResponse {
    'tables': Array<DashboardTableRow> | null;
    'chartData': Array<ChartDataPoint> | null;
    'statistics': DashboardStatistics;
}

