/* tslint:disable */
/* eslint-disable */
/**
 * BotDashboard API
 * API per la gestione del Bot Dashboard con telemetria, comandi e statistiche real-time
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PcCurrentStatus {
    'computer'?: string | null;
    'keyUltimo'?: number;
    'dtUltimo'?: string;
    'account'?: string | null;
    'tavolo'?: string | null;
    'saldoIniziale'?: number;
    'saldoIstantaneo'?: number;
    'margine'?: number;
    'margineMin'?: number;
    'margineMax'?: number;
    'mediaOra'?: number;
    'valoreGiocato'?: number;
    'colpoMartingala'?: number;
    'stato'?: string | null;
    'colore'?: string | null;
    'allarme'?: boolean;
    'mazzo'?: string | null;
    'pbt'?: string | null;
    'pbtHistory'?: Array<string> | null;
    'ore'?: number;
    'lastAdvice'?: string | null;
    'lastAction'?: number;
    'mazzoCalcolato'?: string | null;
    'lastUpdate'?: string;
    'lastInfo'?: string | null;
    'chosenColor'?: string | null;
}

