/* tslint:disable */
/* eslint-disable */
/**
 * BotDashboard API
 * API per la gestione del Bot Dashboard con telemetria, comandi e statistiche real-time
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

export interface PcStart {
    'id'?: number;
    'pc'?: string | null;
    'startDateTime'?: string;
    'stopDateTime'?: string | null;
    'durationMinutes'?: number | null;
    'startReason'?: string | null;
    'stopReason'?: string | null;
    'botVersion'?: string | null;
    'initialBalance'?: number | null;
    'finalBalance'?: number | null;
    'sessionProfit'?: number | null;
    'isActive'?: boolean;
    'json'?: string | null;
    'notes'?: string | null;
    'idUser'?: number | null;
    'user'?: User;
}

