/* tslint:disable */
/* eslint-disable */
/**
 * BotDashboard API
 * API per la gestione del Bot Dashboard con telemetria, comandi e statistiche real-time
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UserRolesAndPermissionsResponse {
    'userId'?: string | null;
    'userName'?: string | null;
    'roles'?: Array<string> | null;
    'permissions'?: Array<string> | null;
    'isAdmin'?: boolean;
}

