# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - eugenioapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build with dotnet
        working-directory: ./WebApi  # ✅ Specifica la cartella del progetto
        run: dotnet build --configuration Release

      - name: dotnet publish
        working-directory: ./WebApi  # ✅ Specifica la cartella del progetto
        run: dotnet publish -c Release -o ${{github.workspace}}/publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{github.workspace}}/publish  # ✅ Path corretto

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5177DD3612F74DDDB6B6DBA063FAA2EB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0F4A00B9D7E4499E9A7199DA190FE10A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7C33F9C1939543E289ED5F4796B1C873 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'eugenioapi'
          slot-name: 'Production'
          package: .
